/**
 * aos init — Initialize AOS configuration in the current project.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { c, type ParsedArgs } from "../colors";

const HELP = `
${c.bold("aos init")} — Initialize AOS in the current project

${c.bold("USAGE")}
  aos init [--adapter <adapter>]

${c.bold("OPTIONS")}
  --adapter <name>    Adapter to use: pi (default), claude-code, gemini

${c.bold("DESCRIPTION")}
  Creates an .aos/ configuration directory in the current project with
  a default config.yaml. This is the first step to running AOS deliberations.

${c.bold("EXAMPLES")}
  aos init
  aos init --adapter pi
  aos init --adapter claude-code
`;

const VALID_ADAPTERS = ["pi", "claude-code", "gemini"];

function generateConfig(adapter: string): string {
  return `# AOS Framework Configuration
# Generated by: aos init
# Adapter: ${adapter}

adapter: ${adapter}

models:
  economy: anthropic/claude-haiku-4-5
  standard: anthropic/claude-sonnet-4-6
  premium: anthropic/claude-opus-4-6

editor: code
`;
}

export async function initCommand(args: ParsedArgs): Promise<void> {
  if (args.flags.help) {
    console.log(HELP);
    return;
  }

  const adapter = (args.flags.adapter as string) || "pi";

  if (!VALID_ADAPTERS.includes(adapter)) {
    console.error(c.red(`Invalid adapter: "${adapter}". Valid adapters: ${VALID_ADAPTERS.join(", ")}`));
    process.exit(1);
  }

  const cwd = process.cwd();
  const aosDir = join(cwd, ".aos");
  const configPath = join(aosDir, "config.yaml");

  if (existsSync(configPath)) {
    console.log(c.yellow("AOS is already initialized in this project."));
    console.log(c.dim(`  Config: ${configPath}`));
    console.log(c.dim(`  To reinitialize, remove the .aos/ directory first.`));
    return;
  }

  // Create .aos directory
  mkdirSync(aosDir, { recursive: true });

  // Write config
  writeFileSync(configPath, generateConfig(adapter), "utf-8");

  console.log(`
${c.green("AOS initialized successfully!")}

${c.bold("Configuration")}
  Directory: ${c.cyan(aosDir)}
  Config:    ${c.cyan(configPath)}
  Adapter:   ${c.cyan(adapter)}

${c.bold("Getting Started")}
  1. Write a brief describing your strategic problem
     ${c.dim("See core/briefs/sample-product-decision/brief.md for an example")}

  2. Run a deliberation session:
     ${c.cyan("aos run strategic-council --brief path/to/your/brief.md")}

  3. Or list available profiles and agents:
     ${c.cyan("aos list")}

${c.bold("Customization")}
  Create custom agents:   ${c.cyan("aos create agent <name>")}
  Create custom profiles: ${c.cyan("aos create profile <name>")}
  Create domain packs:    ${c.cyan("aos create domain <name>")}
  Validate everything:    ${c.cyan("aos validate")}
`);
}
